language: c
compiler:
  - gcc
  - clang

git:
  depth: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "RV+pdOhl+9krZz7BfZRZqLgEbMNOvfw2MaGJH5h7kSs0pBbdH+YXp7TrGwk0G/Jz3oSKczPve1tWCk06ive0Ngb7me4EfEpX62xziS1ew9yaHpyQxe4sr4lLufZerX1tg0nwDPTS5AiAj2hHlGGQqoMnAkNpWAx15sH1IvUtFOdd/ji1KUbeO3ItF6+tMPl+w9oJa29pOKzEzNMlKtApZYeWT+p0tHVmo2XgYaYMR9+2qe7YbO4LfNcvlSbjc1OE7NnRIZx1yhp9evMfdpdWbzfRc17kZ1pwWO4ZnAKWj30buzI2k0ZgzpdRWO43Zn+913Bc5zJAzO3H+6g78DAJyxqZho3x4d5Mb61TV1g6J4SVnrJiVDKLl57dbvEG+RYDV2/drzDpInkeooVUn2WNacMLV/qYbYVBU4givYBUnAgCzaW5YQuDR14IBNbXxPj/rN5SBB4uwDvAWqcI9WoSI6K3AbF4QX86U6IRqqncfRszZQipMFycduwAxkvK621voA8TxrhoI5BsWxEpqHZsu6URBVbM1/k2QtV273i5ezCECCTy/VBUygUtXGo0JnsoJcBpna4/vqYTUeFS2KbXCKo3TpYAsvy6cHjMt+JseVI29FjueU0C0J1fNyusxRD/9xsYVx8Xt1IC3WD+r64KRIHqzsxY9rCWLONADOUVKjc="

before_install:
  # Coverity scan should only be executed for compiler gcc (which must be the first one in the list)
  - if ([[ "${TRAVIS_JOB_NUMBER##*.}" != "1" ]] && [[ "${TRAVIS_BRANCH}" == "coverity_scan" ]]); then false ; fi
  # install needed packages
  - sudo apt-get update
  - sudo apt-get install fakeroot rpm dpkg debhelper

addons:
  coverity_scan:
    project:
      name: "versat/cntlm"
      description: "Cntlm is an NTLM / NTLM Session Response / NTLMv2 authenticating HTTP proxy."
    build_command_prepend: "make distclean && ./configure"
    build_command: "make"
    branch_pattern: coverity_scan
  sonarcloud:
    organization: "versat"

script:
  # Verify normal build
  - ./configure
  - make
  - make distclean
  # Verify debug build
  - ./configure
  - make DEBUG=1
  - make distclean
  # Verify package creation and installation
  - ./configure
  - make rpm
  - make deb
  - make clean
  - sudo make install
  - sudo make uninstall
  - make distclean
  # Build via scan-build
  - ./configure
  - scan-build --force-analyze-debug-code make
  # SonarCloud build and scan
  - ./configure
  - make clean
  - build-wrapper-linux-x86-64 --out-dir bw-output make
  - sonar-scanner -Dsonar.projectVersion="$(head -n 1 VERSION)"
